#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 152
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 9

enum {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_if = 4,
  anon_sym_for = 5,
  anon_sym_while = 6,
  sym_identifier = 7,
  sym_vector_access = 8,
  anon_sym_SEMI = 9,
  sym__eq = 10,
  sym__operator = 11,
  sym__number = 12,
  sym_end = 13,
  sym_function_keyword = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym__and = 17,
  sym__or = 18,
  sym__not = 19,
  sym__diff = 20,
  sym__comparator_equal = 21,
  anon_sym_true = 22,
  anon_sym_false = 23,
  sym_source_file = 24,
  sym_structure = 25,
  sym_function_definition = 26,
  sym_bool = 27,
  sym_operation = 28,
  sym_expression = 29,
  sym_parameter_list = 30,
  sym_argument_list = 31,
  sym_function_name = 32,
  sym_block = 33,
  sym_structure_keyword = 34,
  sym_factor = 35,
  sym_function_call = 36,
  sym__semi_colon = 37,
  sym_vector_definition = 38,
  sym__bool_keywords = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_parameter_list_repeat1 = 41,
  aux_sym_argument_list_repeat1 = 42,
  aux_sym_block_repeat1 = 43,
  aux_sym_vector_definition_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_if] = "if",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [sym_identifier] = "identifier",
  [sym_vector_access] = "vector_access",
  [anon_sym_SEMI] = ";",
  [sym__eq] = "_eq",
  [sym__operator] = "_operator",
  [sym__number] = "_number",
  [sym_end] = "end",
  [sym_function_keyword] = "function_keyword",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__and] = "_and",
  [sym__or] = "_or",
  [sym__not] = "_not",
  [sym__diff] = "_diff",
  [sym__comparator_equal] = "_comparator_equal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_structure] = "structure",
  [sym_function_definition] = "function_definition",
  [sym_bool] = "bool",
  [sym_operation] = "operation",
  [sym_expression] = "expression",
  [sym_parameter_list] = "parameter_list",
  [sym_argument_list] = "argument_list",
  [sym_function_name] = "function_name",
  [sym_block] = "block",
  [sym_structure_keyword] = "structure_keyword",
  [sym_factor] = "factor",
  [sym_function_call] = "function_call",
  [sym__semi_colon] = "_semi_colon",
  [sym_vector_definition] = "vector_definition",
  [sym__bool_keywords] = "_bool_keywords",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_vector_definition_repeat1] = "vector_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [sym_identifier] = sym_identifier,
  [sym_vector_access] = sym_vector_access,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__eq] = sym__eq,
  [sym__operator] = sym__operator,
  [sym__number] = sym__number,
  [sym_end] = sym_end,
  [sym_function_keyword] = sym_function_keyword,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__and] = sym__and,
  [sym__or] = sym__or,
  [sym__not] = sym__not,
  [sym__diff] = sym__diff,
  [sym__comparator_equal] = sym__comparator_equal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_structure] = sym_structure,
  [sym_function_definition] = sym_function_definition,
  [sym_bool] = sym_bool,
  [sym_operation] = sym_operation,
  [sym_expression] = sym_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_argument_list] = sym_argument_list,
  [sym_function_name] = sym_function_name,
  [sym_block] = sym_block,
  [sym_structure_keyword] = sym_structure_keyword,
  [sym_factor] = sym_factor,
  [sym_function_call] = sym_function_call,
  [sym__semi_colon] = sym__semi_colon,
  [sym_vector_definition] = sym_vector_definition,
  [sym__bool_keywords] = sym__bool_keywords,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_vector_definition_repeat1] = aux_sym_vector_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_vector_access] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__eq] = {
    .visible = false,
    .named = true,
  },
  [sym__operator] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [sym_function_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__and] = {
    .visible = false,
    .named = true,
  },
  [sym__or] = {
    .visible = false,
    .named = true,
  },
  [sym__not] = {
    .visible = false,
    .named = true,
  },
  [sym__diff] = {
    .visible = false,
    .named = true,
  },
  [sym__comparator_equal] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_structure] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_structure_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__semi_colon] = {
    .visible = false,
    .named = true,
  },
  [sym_vector_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__bool_keywords] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_end = 1,
  field_function_keyword = 2,
  field_function_name = 3,
  field_return_variable = 4,
  field_structure_keyword = 5,
  field_variable_name = 6,
  field_vector_access = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_end] = "end",
  [field_function_keyword] = "function_keyword",
  [field_function_name] = "function_name",
  [field_return_variable] = "return_variable",
  [field_structure_keyword] = "structure_keyword",
  [field_variable_name] = "variable_name",
  [field_vector_access] = "vector_access",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 4},
  [8] = {.index = 16, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_variable_name, 0},
  [1] =
    {field_vector_access, 0},
  [2] =
    {field_end, 2},
    {field_structure_keyword, 0},
  [4] =
    {field_end, 3},
    {field_function_keyword, 0},
    {field_function_name, 1},
  [7] =
    {field_end, 3},
    {field_structure_keyword, 0},
  [9] =
    {field_end, 4},
    {field_function_keyword, 0},
    {field_function_name, 1},
  [12] =
    {field_end, 5},
    {field_function_keyword, 0},
    {field_function_name, 3},
    {field_return_variable, 1},
  [16] =
    {field_end, 6},
    {field_function_keyword, 0},
    {field_function_name, 3},
    {field_return_variable, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '!') ADVANCE(60);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '[') ADVANCE(55);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 't') ADVANCE(40);
      if (lookahead == 'w') ADVANCE(29);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 'w') ADVANCE(29);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(59);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '[') ADVANCE(55);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '<') ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(59);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 't') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(57);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(61);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(62);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == '|') ADVANCE(58);
      END_STATE();
    case 12:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ';') ADVANCE(48);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 'w') ADVANCE(29);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13)
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_for);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_while);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'a') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == 'u') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'a') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'c') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'd') ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'f') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'h') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == 'u') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 's') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 't') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_vector_access);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__eq);
      if (lookahead == '=') ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__operator);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_end);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_function_keyword);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__and);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__or);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__not);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__not);
      if (lookahead == '=') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__diff);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__comparator_equal);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '(') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 13},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 13},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 13},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 13},
  [90] = {.lex_state = 13},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 13},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 13},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 13},
  [106] = {.lex_state = 13},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 13},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 13},
  [123] = {.lex_state = 13},
  [124] = {.lex_state = 13},
  [125] = {.lex_state = 13},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 2},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 2},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 9},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 9},
  [143] = {.lex_state = 2},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 9},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 2},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 9},
  [151] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_vector_access] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym__eq] = ACTIONS(1),
    [sym__operator] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym_end] = ACTIONS(1),
    [sym_function_keyword] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__and] = ACTIONS(1),
    [sym__or] = ACTIONS(1),
    [sym__not] = ACTIONS(1),
    [sym__diff] = ACTIONS(1),
    [sym__comparator_equal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(144),
    [sym_structure] = STATE(9),
    [sym_function_definition] = STATE(9),
    [sym_expression] = STATE(9),
    [sym_function_name] = STATE(136),
    [sym_structure_keyword] = STATE(8),
    [sym_function_call] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_vector_access] = ACTIONS(9),
    [sym_function_keyword] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(19), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    STATE(142), 1,
      sym_block,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(29), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(17), 5,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [33] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(21), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    STATE(139), 1,
      sym_block,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(29), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(17), 5,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [66] = 8,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_vector_access,
    ACTIONS(34), 1,
      sym_function_keyword,
    STATE(8), 1,
      sym_structure_keyword,
    STATE(136), 1,
      sym_function_name,
    ACTIONS(25), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(4), 5,
      sym_structure,
      sym_function_definition,
      sym_expression,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [97] = 3,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
    ACTIONS(17), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [118] = 4,
    ACTIONS(45), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      sym__semi_colon,
    ACTIONS(41), 6,
      ts_builtin_sym_end,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(43), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [141] = 11,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(53), 1,
      sym__not,
    STATE(2), 1,
      sym_operation,
    STATE(17), 1,
      sym_function_call,
    STATE(123), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 3,
      sym_bool,
      sym_expression,
      sym__bool_keywords,
  [178] = 11,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(53), 1,
      sym__not,
    STATE(3), 1,
      sym_operation,
    STATE(17), 1,
      sym_function_call,
    STATE(123), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    ACTIONS(57), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 3,
      sym_bool,
      sym_expression,
      sym__bool_keywords,
  [215] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_vector_access,
    ACTIONS(11), 1,
      sym_function_keyword,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_structure_keyword,
    STATE(136), 1,
      sym_function_name,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(4), 5,
      sym_structure,
      sym_function_definition,
      sym_expression,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [246] = 3,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
    ACTIONS(17), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [267] = 4,
    ACTIONS(61), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      sym__semi_colon,
    ACTIONS(41), 6,
      anon_sym_RPAREN,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(43), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [290] = 3,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(65), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [310] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(69), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(71), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [330] = 2,
    ACTIONS(77), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
    ACTIONS(75), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [348] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(63), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(65), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [368] = 2,
    ACTIONS(81), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
    ACTIONS(79), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [386] = 2,
    ACTIONS(39), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
    ACTIONS(17), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [404] = 2,
    ACTIONS(77), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [422] = 2,
    ACTIONS(81), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [440] = 3,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(71), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [460] = 2,
    ACTIONS(85), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
    ACTIONS(83), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [478] = 2,
    ACTIONS(39), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
    ACTIONS(17), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [496] = 2,
    ACTIONS(85), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [514] = 7,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(21), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    STATE(139), 1,
      sym_block,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(29), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
  [540] = 7,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(87), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    STATE(150), 1,
      sym_block,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(29), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
  [566] = 7,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(89), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    STATE(145), 1,
      sym_block,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(29), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
  [592] = 7,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(19), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    STATE(142), 1,
      sym_block,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(29), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
  [618] = 6,
    ACTIONS(94), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_vector_access,
    ACTIONS(100), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    ACTIONS(91), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(28), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
  [641] = 6,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_vector_access,
    ACTIONS(102), 1,
      sym_end,
    STATE(7), 1,
      sym_structure_keyword,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(28), 3,
      sym_structure,
      sym_expression,
      aux_sym_block_repeat1,
  [664] = 5,
    ACTIONS(17), 1,
      sym__operator,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      anon_sym_SEMI,
    STATE(77), 1,
      sym__semi_colon,
    ACTIONS(106), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [685] = 5,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      anon_sym_SEMI,
    STATE(77), 1,
      sym__semi_colon,
    ACTIONS(106), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [706] = 5,
    ACTIONS(17), 1,
      sym__operator,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_SEMI,
    STATE(108), 1,
      sym__semi_colon,
    ACTIONS(112), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [727] = 5,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_SEMI,
    STATE(108), 1,
      sym__semi_colon,
    ACTIONS(112), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [748] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(120), 1,
      anon_sym_RBRACK,
    ACTIONS(122), 1,
      sym__not,
    STATE(47), 1,
      aux_sym_vector_definition_repeat1,
    STATE(104), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [774] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    ACTIONS(128), 1,
      sym__comparator_equal,
    ACTIONS(126), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [792] = 4,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      anon_sym_SEMI,
    STATE(77), 1,
      sym__semi_colon,
    ACTIONS(106), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [810] = 4,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_SEMI,
    STATE(108), 1,
      sym__semi_colon,
    ACTIONS(112), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [828] = 9,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    ACTIONS(134), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_function_call,
    STATE(56), 1,
      sym_factor,
    STATE(57), 1,
      sym_operation,
    STATE(65), 1,
      sym_vector_definition,
    STATE(133), 1,
      sym_function_name,
  [856] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [882] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [908] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [934] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [960] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [986] = 9,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_LBRACK,
    ACTIONS(150), 1,
      sym__not,
    STATE(17), 1,
      sym_function_call,
    STATE(32), 1,
      sym_operation,
    STATE(33), 1,
      sym_factor,
    STATE(37), 1,
      sym_vector_definition,
    STATE(136), 1,
      sym_function_name,
  [1014] = 9,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_LBRACK,
    ACTIONS(150), 1,
      sym__not,
    STATE(17), 1,
      sym_function_call,
    STATE(30), 1,
      sym_operation,
    STATE(31), 1,
      sym_factor,
    STATE(36), 1,
      sym_vector_definition,
    STATE(136), 1,
      sym_function_name,
  [1042] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      sym__comparator_equal,
    ACTIONS(154), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1060] = 8,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(161), 1,
      sym__number,
    ACTIONS(164), 1,
      anon_sym_RBRACK,
    ACTIONS(166), 1,
      sym__not,
    STATE(47), 1,
      aux_sym_vector_definition_repeat1,
    STATE(104), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1086] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_vector_definition_repeat1,
    STATE(104), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1112] = 9,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    ACTIONS(134), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_function_call,
    STATE(53), 1,
      sym_factor,
    STATE(54), 1,
      sym_operation,
    STATE(66), 1,
      sym_vector_definition,
    STATE(133), 1,
      sym_function_name,
  [1140] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(175), 1,
      sym__comparator_equal,
    ACTIONS(173), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1158] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(181), 1,
      sym__comparator_equal,
    ACTIONS(179), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1176] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      aux_sym_vector_definition_repeat1,
    STATE(104), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1202] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(185), 1,
      anon_sym_SEMI,
    STATE(116), 1,
      sym__semi_colon,
    ACTIONS(112), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1220] = 4,
    ACTIONS(17), 1,
      sym__operator,
    ACTIONS(185), 1,
      anon_sym_SEMI,
    STATE(116), 1,
      sym__semi_colon,
    ACTIONS(112), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1238] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      aux_sym_vector_definition_repeat1,
    STATE(104), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1264] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(189), 1,
      anon_sym_SEMI,
    STATE(115), 1,
      sym__semi_colon,
    ACTIONS(106), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1282] = 4,
    ACTIONS(17), 1,
      sym__operator,
    ACTIONS(189), 1,
      anon_sym_SEMI,
    STATE(115), 1,
      sym__semi_colon,
    ACTIONS(106), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1300] = 2,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1314] = 8,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1340] = 8,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(198), 1,
      sym__number,
    ACTIONS(201), 1,
      sym__not,
    STATE(60), 1,
      aux_sym_argument_list_repeat1,
    STATE(109), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1366] = 3,
    ACTIONS(204), 1,
      anon_sym_SEMI,
    STATE(68), 1,
      sym__semi_colon,
    ACTIONS(41), 7,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1382] = 1,
    ACTIONS(17), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1393] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    ACTIONS(208), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1408] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    ACTIONS(212), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1423] = 3,
    ACTIONS(189), 1,
      anon_sym_SEMI,
    STATE(115), 1,
      sym__semi_colon,
    ACTIONS(106), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1438] = 3,
    ACTIONS(185), 1,
      anon_sym_SEMI,
    STATE(116), 1,
      sym__semi_colon,
    ACTIONS(112), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1453] = 1,
    ACTIONS(79), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1464] = 1,
    ACTIONS(75), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1475] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1490] = 2,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(216), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1503] = 2,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(220), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1516] = 1,
    ACTIONS(83), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1527] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1542] = 2,
    ACTIONS(222), 1,
      sym__operator,
    ACTIONS(63), 7,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1555] = 2,
    ACTIONS(222), 1,
      sym__operator,
    ACTIONS(69), 7,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_identifier,
      anon_sym_SEMI,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1568] = 2,
    ACTIONS(218), 1,
      anon_sym_SEMI,
    ACTIONS(220), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1580] = 2,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
    ACTIONS(226), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1592] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(136), 1,
      sym_function_name,
    STATE(151), 1,
      sym_factor,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [1612] = 2,
    ACTIONS(228), 3,
      anon_sym_LPAREN,
      sym__number,
      sym__not,
    ACTIONS(230), 4,
      sym_identifier,
      sym_vector_access,
      anon_sym_true,
      anon_sym_false,
  [1624] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(136), 1,
      sym_function_name,
    STATE(141), 1,
      sym_factor,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [1644] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(73), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1664] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(46), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1684] = 2,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
    ACTIONS(234), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1696] = 6,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    STATE(75), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1716] = 6,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    STATE(74), 1,
      sym_factor,
    STATE(134), 1,
      sym_function_name,
    STATE(62), 2,
      sym_operation,
      sym_function_call,
  [1736] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(69), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1756] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(50), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1776] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(122), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [1796] = 3,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(236), 1,
      sym__eq,
    ACTIONS(17), 5,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [1810] = 2,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
    ACTIONS(240), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1822] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(136), 1,
      sym_function_name,
    STATE(146), 1,
      sym_factor,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [1842] = 2,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1854] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(15), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1874] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(64), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1894] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(51), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1914] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(63), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [1934] = 2,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    ACTIONS(216), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [1946] = 2,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
    ACTIONS(248), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [1958] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(124), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [1978] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(20), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [1998] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(13), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [2018] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(125), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [2038] = 6,
    ACTIONS(53), 1,
      sym__not,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym__number,
    STATE(35), 1,
      sym_factor,
    STATE(133), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [2058] = 3,
    ACTIONS(222), 1,
      sym__operator,
    ACTIONS(250), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(252), 4,
      sym_identifier,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [2072] = 2,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
    ACTIONS(256), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [2084] = 2,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
    ACTIONS(260), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [2096] = 6,
    ACTIONS(51), 1,
      sym__number,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__not,
    STATE(12), 1,
      sym_factor,
    STATE(136), 1,
      sym_function_name,
    STATE(17), 2,
      sym_operation,
      sym_function_call,
  [2116] = 2,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
    ACTIONS(264), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_function_keyword,
  [2128] = 3,
    ACTIONS(222), 1,
      sym__operator,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(266), 4,
      anon_sym_RPAREN,
      sym_identifier,
      sym__number,
      sym__not,
  [2141] = 1,
    ACTIONS(270), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2150] = 1,
    ACTIONS(126), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2159] = 1,
    ACTIONS(154), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2168] = 1,
    ACTIONS(272), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2177] = 1,
    ACTIONS(212), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2186] = 1,
    ACTIONS(226), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2195] = 1,
    ACTIONS(264), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2204] = 1,
    ACTIONS(244), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2213] = 1,
    ACTIONS(274), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2222] = 1,
    ACTIONS(248), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2231] = 1,
    ACTIONS(208), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2240] = 1,
    ACTIONS(173), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym_identifier,
      sym_vector_access,
      sym_end,
  [2249] = 3,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(278), 1,
      sym__comparator_equal,
    ACTIONS(276), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2261] = 3,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(282), 1,
      sym__comparator_equal,
    ACTIONS(280), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2273] = 2,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(284), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2282] = 2,
    ACTIONS(67), 1,
      sym__operator,
    ACTIONS(286), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2291] = 1,
    ACTIONS(164), 4,
      sym_identifier,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [2298] = 1,
    ACTIONS(193), 4,
      anon_sym_RPAREN,
      sym_identifier,
      sym__number,
      sym__not,
  [2305] = 3,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    ACTIONS(290), 1,
      sym_identifier,
    STATE(130), 1,
      aux_sym_parameter_list_repeat1,
  [2315] = 3,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
    ACTIONS(294), 1,
      sym__eq,
    STATE(25), 1,
      sym_parameter_list,
  [2325] = 3,
    ACTIONS(290), 1,
      sym_identifier,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    STATE(132), 1,
      aux_sym_parameter_list_repeat1,
  [2335] = 2,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(298), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2343] = 3,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    ACTIONS(304), 1,
      sym_identifier,
    STATE(132), 1,
      aux_sym_parameter_list_repeat1,
  [2353] = 2,
    ACTIONS(307), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_argument_list,
  [2360] = 2,
    ACTIONS(309), 1,
      anon_sym_LPAREN,
    STATE(61), 1,
      sym_argument_list,
  [2367] = 1,
    ACTIONS(302), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2372] = 2,
    ACTIONS(311), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_argument_list,
  [2379] = 2,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(313), 1,
      sym__eq,
  [2386] = 2,
    ACTIONS(292), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_parameter_list,
  [2393] = 1,
    ACTIONS(315), 1,
      sym_end,
  [2397] = 1,
    ACTIONS(317), 1,
      sym__eq,
  [2401] = 1,
    ACTIONS(319), 1,
      sym__operator,
  [2405] = 1,
    ACTIONS(321), 1,
      sym_end,
  [2409] = 1,
    ACTIONS(323), 1,
      sym_identifier,
  [2413] = 1,
    ACTIONS(325), 1,
      ts_builtin_sym_end,
  [2417] = 1,
    ACTIONS(327), 1,
      sym_end,
  [2421] = 1,
    ACTIONS(329), 1,
      sym__operator,
  [2425] = 1,
    ACTIONS(331), 1,
      sym_identifier,
  [2429] = 1,
    ACTIONS(333), 1,
      sym__eq,
  [2433] = 1,
    ACTIONS(335), 1,
      sym__eq,
  [2437] = 1,
    ACTIONS(337), 1,
      sym_end,
  [2441] = 1,
    ACTIONS(339), 1,
      sym__operator,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 141,
  [SMALL_STATE(8)] = 178,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 246,
  [SMALL_STATE(11)] = 267,
  [SMALL_STATE(12)] = 290,
  [SMALL_STATE(13)] = 310,
  [SMALL_STATE(14)] = 330,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 368,
  [SMALL_STATE(17)] = 386,
  [SMALL_STATE(18)] = 404,
  [SMALL_STATE(19)] = 422,
  [SMALL_STATE(20)] = 440,
  [SMALL_STATE(21)] = 460,
  [SMALL_STATE(22)] = 478,
  [SMALL_STATE(23)] = 496,
  [SMALL_STATE(24)] = 514,
  [SMALL_STATE(25)] = 540,
  [SMALL_STATE(26)] = 566,
  [SMALL_STATE(27)] = 592,
  [SMALL_STATE(28)] = 618,
  [SMALL_STATE(29)] = 641,
  [SMALL_STATE(30)] = 664,
  [SMALL_STATE(31)] = 685,
  [SMALL_STATE(32)] = 706,
  [SMALL_STATE(33)] = 727,
  [SMALL_STATE(34)] = 748,
  [SMALL_STATE(35)] = 774,
  [SMALL_STATE(36)] = 792,
  [SMALL_STATE(37)] = 810,
  [SMALL_STATE(38)] = 828,
  [SMALL_STATE(39)] = 856,
  [SMALL_STATE(40)] = 882,
  [SMALL_STATE(41)] = 908,
  [SMALL_STATE(42)] = 934,
  [SMALL_STATE(43)] = 960,
  [SMALL_STATE(44)] = 986,
  [SMALL_STATE(45)] = 1014,
  [SMALL_STATE(46)] = 1042,
  [SMALL_STATE(47)] = 1060,
  [SMALL_STATE(48)] = 1086,
  [SMALL_STATE(49)] = 1112,
  [SMALL_STATE(50)] = 1140,
  [SMALL_STATE(51)] = 1158,
  [SMALL_STATE(52)] = 1176,
  [SMALL_STATE(53)] = 1202,
  [SMALL_STATE(54)] = 1220,
  [SMALL_STATE(55)] = 1238,
  [SMALL_STATE(56)] = 1264,
  [SMALL_STATE(57)] = 1282,
  [SMALL_STATE(58)] = 1300,
  [SMALL_STATE(59)] = 1314,
  [SMALL_STATE(60)] = 1340,
  [SMALL_STATE(61)] = 1366,
  [SMALL_STATE(62)] = 1382,
  [SMALL_STATE(63)] = 1393,
  [SMALL_STATE(64)] = 1408,
  [SMALL_STATE(65)] = 1423,
  [SMALL_STATE(66)] = 1438,
  [SMALL_STATE(67)] = 1453,
  [SMALL_STATE(68)] = 1464,
  [SMALL_STATE(69)] = 1475,
  [SMALL_STATE(70)] = 1490,
  [SMALL_STATE(71)] = 1503,
  [SMALL_STATE(72)] = 1516,
  [SMALL_STATE(73)] = 1527,
  [SMALL_STATE(74)] = 1542,
  [SMALL_STATE(75)] = 1555,
  [SMALL_STATE(76)] = 1568,
  [SMALL_STATE(77)] = 1580,
  [SMALL_STATE(78)] = 1592,
  [SMALL_STATE(79)] = 1612,
  [SMALL_STATE(80)] = 1624,
  [SMALL_STATE(81)] = 1644,
  [SMALL_STATE(82)] = 1664,
  [SMALL_STATE(83)] = 1684,
  [SMALL_STATE(84)] = 1696,
  [SMALL_STATE(85)] = 1716,
  [SMALL_STATE(86)] = 1736,
  [SMALL_STATE(87)] = 1756,
  [SMALL_STATE(88)] = 1776,
  [SMALL_STATE(89)] = 1796,
  [SMALL_STATE(90)] = 1810,
  [SMALL_STATE(91)] = 1822,
  [SMALL_STATE(92)] = 1842,
  [SMALL_STATE(93)] = 1854,
  [SMALL_STATE(94)] = 1874,
  [SMALL_STATE(95)] = 1894,
  [SMALL_STATE(96)] = 1914,
  [SMALL_STATE(97)] = 1934,
  [SMALL_STATE(98)] = 1946,
  [SMALL_STATE(99)] = 1958,
  [SMALL_STATE(100)] = 1978,
  [SMALL_STATE(101)] = 1998,
  [SMALL_STATE(102)] = 2018,
  [SMALL_STATE(103)] = 2038,
  [SMALL_STATE(104)] = 2058,
  [SMALL_STATE(105)] = 2072,
  [SMALL_STATE(106)] = 2084,
  [SMALL_STATE(107)] = 2096,
  [SMALL_STATE(108)] = 2116,
  [SMALL_STATE(109)] = 2128,
  [SMALL_STATE(110)] = 2141,
  [SMALL_STATE(111)] = 2150,
  [SMALL_STATE(112)] = 2159,
  [SMALL_STATE(113)] = 2168,
  [SMALL_STATE(114)] = 2177,
  [SMALL_STATE(115)] = 2186,
  [SMALL_STATE(116)] = 2195,
  [SMALL_STATE(117)] = 2204,
  [SMALL_STATE(118)] = 2213,
  [SMALL_STATE(119)] = 2222,
  [SMALL_STATE(120)] = 2231,
  [SMALL_STATE(121)] = 2240,
  [SMALL_STATE(122)] = 2249,
  [SMALL_STATE(123)] = 2261,
  [SMALL_STATE(124)] = 2273,
  [SMALL_STATE(125)] = 2282,
  [SMALL_STATE(126)] = 2291,
  [SMALL_STATE(127)] = 2298,
  [SMALL_STATE(128)] = 2305,
  [SMALL_STATE(129)] = 2315,
  [SMALL_STATE(130)] = 2325,
  [SMALL_STATE(131)] = 2335,
  [SMALL_STATE(132)] = 2343,
  [SMALL_STATE(133)] = 2353,
  [SMALL_STATE(134)] = 2360,
  [SMALL_STATE(135)] = 2367,
  [SMALL_STATE(136)] = 2372,
  [SMALL_STATE(137)] = 2379,
  [SMALL_STATE(138)] = 2386,
  [SMALL_STATE(139)] = 2393,
  [SMALL_STATE(140)] = 2397,
  [SMALL_STATE(141)] = 2401,
  [SMALL_STATE(142)] = 2405,
  [SMALL_STATE(143)] = 2409,
  [SMALL_STATE(144)] = 2413,
  [SMALL_STATE(145)] = 2417,
  [SMALL_STATE(146)] = 2421,
  [SMALL_STATE(147)] = 2425,
  [SMALL_STATE(148)] = 2429,
  [SMALL_STATE(149)] = 2433,
  [SMALL_STATE(150)] = 2437,
  [SMALL_STATE(151)] = 2441,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(148),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(149),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(79),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(137),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(148),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(147),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 4),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(79),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(140),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(149),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, .production_id = 1),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, .production_id = 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, .production_id = 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, .production_id = 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(58),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(62),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(78),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 6),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(58),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(62),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(78),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 8),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 7),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_definition, 3),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector_definition, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_definition, 2),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector_definition, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4, .production_id = 1),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4, .production_id = 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure_keyword, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_structure_keyword, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, .production_id = 7),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, .production_id = 7),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, .production_id = 8),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, .production_id = 8),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure, 3, .production_id = 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_structure, 3, .production_id = 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure, 4, .production_id = 5),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_structure, 4, .production_id = 5),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, .production_id = 6),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, .production_id = 6),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 4),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, .production_id = 4),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4, .production_id = 2),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4, .production_id = 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 9),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(131),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [325] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_matlab(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
