#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_if = 4,
  anon_sym_for = 5,
  anon_sym_while = 6,
  aux_sym_identifier_token1 = 7,
  aux_sym_identifier_token2 = 8,
  anon_sym_SEMI = 9,
  sym__eq = 10,
  sym__operator = 11,
  sym__number = 12,
  sym__end = 13,
  sym__function_keyword = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym__and = 17,
  sym__or = 18,
  sym__not = 19,
  sym__diff = 20,
  sym__comparator_equal = 21,
  sym_source_file = 22,
  sym_structure = 23,
  sym_function_definition = 24,
  sym_bool = 25,
  sym_operation = 26,
  sym_expression = 27,
  sym_parameter_list = 28,
  sym_argument_list = 29,
  sym_function_name = 30,
  sym_return_value = 31,
  sym_block = 32,
  sym__structure_keyword = 33,
  sym_identifier = 34,
  sym_factor = 35,
  sym_function_call = 36,
  sym__semi_colon = 37,
  sym_vector_definition = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_parameter_list_repeat1 = 40,
  aux_sym_argument_list_repeat1 = 41,
  aux_sym_block_repeat1 = 42,
  aux_sym_vector_definition_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_if] = "if",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [anon_sym_SEMI] = ";",
  [sym__eq] = "_eq",
  [sym__operator] = "_operator",
  [sym__number] = "_number",
  [sym__end] = "_end",
  [sym__function_keyword] = "_function_keyword",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__and] = "_and",
  [sym__or] = "_or",
  [sym__not] = "_not",
  [sym__diff] = "_diff",
  [sym__comparator_equal] = "_comparator_equal",
  [sym_source_file] = "source_file",
  [sym_structure] = "structure",
  [sym_function_definition] = "function_definition",
  [sym_bool] = "bool",
  [sym_operation] = "operation",
  [sym_expression] = "expression",
  [sym_parameter_list] = "parameter_list",
  [sym_argument_list] = "argument_list",
  [sym_function_name] = "function_name",
  [sym_return_value] = "return_value",
  [sym_block] = "block",
  [sym__structure_keyword] = "_structure_keyword",
  [sym_identifier] = "identifier",
  [sym_factor] = "factor",
  [sym_function_call] = "function_call",
  [sym__semi_colon] = "_semi_colon",
  [sym_vector_definition] = "vector_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_vector_definition_repeat1] = "vector_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__eq] = sym__eq,
  [sym__operator] = sym__operator,
  [sym__number] = sym__number,
  [sym__end] = sym__end,
  [sym__function_keyword] = sym__function_keyword,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__and] = sym__and,
  [sym__or] = sym__or,
  [sym__not] = sym__not,
  [sym__diff] = sym__diff,
  [sym__comparator_equal] = sym__comparator_equal,
  [sym_source_file] = sym_source_file,
  [sym_structure] = sym_structure,
  [sym_function_definition] = sym_function_definition,
  [sym_bool] = sym_bool,
  [sym_operation] = sym_operation,
  [sym_expression] = sym_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_argument_list] = sym_argument_list,
  [sym_function_name] = sym_function_name,
  [sym_return_value] = sym_return_value,
  [sym_block] = sym_block,
  [sym__structure_keyword] = sym__structure_keyword,
  [sym_identifier] = sym_identifier,
  [sym_factor] = sym_factor,
  [sym_function_call] = sym_function_call,
  [sym__semi_colon] = sym__semi_colon,
  [sym_vector_definition] = sym_vector_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_vector_definition_repeat1] = aux_sym_vector_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__eq] = {
    .visible = false,
    .named = true,
  },
  [sym__operator] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym__end] = {
    .visible = false,
    .named = true,
  },
  [sym__function_keyword] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__and] = {
    .visible = false,
    .named = true,
  },
  [sym__or] = {
    .visible = false,
    .named = true,
  },
  [sym__not] = {
    .visible = false,
    .named = true,
  },
  [sym__diff] = {
    .visible = false,
    .named = true,
  },
  [sym__comparator_equal] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_structure] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym_return_value] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__structure_keyword] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__semi_colon] = {
    .visible = false,
    .named = true,
  },
  [sym_vector_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'w') ADVANCE(20);
      if (lookahead == '|') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '|') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == '|') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(42);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '<') ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == '|') ADVANCE(41);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'w') ADVANCE(20);
      if (lookahead == '|') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          (':' <= lookahead && lookahead <= '>') ||
          lookahead == '^') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_if);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_for);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_while);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'c') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'd') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'f') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'h') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'i') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'i') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'l') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'n') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'n') ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'n') ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'o') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'o') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'r') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 't') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__eq);
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__operator);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__end);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__function_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__and);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__or);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__not);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__not);
      if (lookahead == '=') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__diff);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__comparator_equal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 8},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 8},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 8},
  [85] = {.lex_state = 8},
  [86] = {.lex_state = 8},
  [87] = {.lex_state = 8},
  [88] = {.lex_state = 8},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 8},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 8},
  [109] = {.lex_state = 8},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 8},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 8},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 2},
  [125] = {.lex_state = 2},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [aux_sym_identifier_token2] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym__eq] = ACTIONS(1),
    [sym__operator] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym__end] = ACTIONS(1),
    [sym__function_keyword] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__and] = ACTIONS(1),
    [sym__or] = ACTIONS(1),
    [sym__not] = ACTIONS(1),
    [sym__diff] = ACTIONS(1),
    [sym__comparator_equal] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(140),
    [sym_structure] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_expression] = STATE(4),
    [sym_function_name] = STATE(132),
    [sym__structure_keyword] = STATE(12),
    [sym_identifier] = STATE(131),
    [sym_function_call] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_for] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(5),
    [aux_sym_identifier_token1] = ACTIONS(7),
    [aux_sym_identifier_token2] = ACTIONS(7),
    [sym__function_keyword] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(13), 3,
      aux_sym_identifier_token2,
      sym__eq,
      sym__not,
    ACTIONS(11), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [20] = 8,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym__function_keyword,
    STATE(12), 1,
      sym__structure_keyword,
    STATE(131), 1,
      sym_identifier,
    STATE(132), 1,
      sym_function_name,
    ACTIONS(20), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    ACTIONS(17), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(3), 5,
      sym_structure,
      sym_function_definition,
      sym_expression,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [52] = 8,
    ACTIONS(9), 1,
      sym__function_keyword,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      sym__structure_keyword,
    STATE(131), 1,
      sym_identifier,
    STATE(132), 1,
      sym_function_name,
    ACTIONS(7), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    ACTIONS(5), 3,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
    STATE(3), 5,
      sym_structure,
      sym_function_definition,
      sym_expression,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [84] = 3,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 2,
      aux_sym_identifier_token2,
      sym__not,
    ACTIONS(30), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [105] = 4,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      sym__semi_colon,
    ACTIONS(34), 6,
      ts_builtin_sym_end,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
    ACTIONS(36), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [128] = 2,
    ACTIONS(32), 2,
      aux_sym_identifier_token2,
      sym__not,
    ACTIONS(30), 11,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [146] = 2,
    ACTIONS(42), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
    ACTIONS(40), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [164] = 2,
    ACTIONS(46), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
    ACTIONS(44), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [182] = 2,
    ACTIONS(50), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
    ACTIONS(48), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [200] = 7,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym__end,
    STATE(81), 1,
      sym_block,
    STATE(136), 1,
      sym_identifier,
    ACTIONS(7), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(89), 2,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(54), 4,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym__function_keyword,
  [227] = 11,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(64), 1,
      sym__not,
    STATE(7), 1,
      sym_function_call,
    STATE(13), 1,
      sym_operation,
    STATE(82), 1,
      sym_identifier,
    STATE(108), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(80), 2,
      sym_bool,
      sym_expression,
  [262] = 6,
    ACTIONS(56), 1,
      sym__end,
    STATE(86), 1,
      sym_block,
    STATE(136), 1,
      sym_identifier,
    ACTIONS(7), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(89), 2,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(30), 5,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [287] = 7,
    ACTIONS(56), 1,
      sym__end,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_block,
    STATE(136), 1,
      sym_identifier,
    ACTIONS(7), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(89), 2,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(68), 4,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      sym__function_keyword,
  [314] = 2,
    ACTIONS(13), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(11), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [330] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
    ACTIONS(72), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(25), 1,
      aux_sym_vector_definition_repeat1,
    STATE(77), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [362] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_identifier,
    STATE(24), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [394] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(76), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      sym_identifier,
    STATE(29), 1,
      aux_sym_vector_definition_repeat1,
    STATE(77), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [426] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_identifier,
    STATE(31), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [458] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_identifier,
    STATE(30), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [490] = 10,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    ACTIONS(84), 1,
      aux_sym_identifier_token1,
    ACTIONS(87), 1,
      aux_sym_identifier_token2,
    ACTIONS(90), 1,
      sym__number,
    ACTIONS(93), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(21), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [522] = 10,
    ACTIONS(96), 1,
      aux_sym_identifier_token1,
    ACTIONS(99), 1,
      aux_sym_identifier_token2,
    ACTIONS(102), 1,
      sym__number,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    ACTIONS(107), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(22), 1,
      aux_sym_vector_definition_repeat1,
    STATE(77), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [554] = 3,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(30), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [572] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_identifier,
    STATE(21), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [604] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(112), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      sym_identifier,
    STATE(22), 1,
      aux_sym_vector_definition_repeat1,
    STATE(77), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [636] = 11,
    ACTIONS(114), 1,
      aux_sym_identifier_token1,
    ACTIONS(116), 1,
      aux_sym_identifier_token2,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(120), 1,
      anon_sym_LBRACK,
    ACTIONS(122), 1,
      sym__not,
    STATE(40), 1,
      sym_identifier,
    STATE(41), 1,
      sym_operation,
    STATE(42), 1,
      sym_factor,
    STATE(46), 1,
      sym_vector_definition,
    STATE(61), 1,
      sym_function_call,
    STATE(132), 1,
      sym_function_name,
  [670] = 4,
    ACTIONS(124), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      sym__semi_colon,
    ACTIONS(36), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(34), 6,
      anon_sym_RPAREN,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [690] = 11,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    ACTIONS(132), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_identifier,
    STATE(32), 1,
      sym_function_call,
    STATE(94), 1,
      sym_factor,
    STATE(95), 1,
      sym_operation,
    STATE(103), 1,
      sym_vector_definition,
    STATE(129), 1,
      sym_function_name,
  [724] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      sym_identifier,
    STATE(22), 1,
      aux_sym_vector_definition_repeat1,
    STATE(77), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [756] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_identifier,
    STATE(21), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [788] = 10,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_identifier,
    STATE(21), 1,
      aux_sym_argument_list_repeat1,
    STATE(83), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [820] = 2,
    ACTIONS(32), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(30), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [835] = 2,
    ACTIONS(50), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(48), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [850] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(142), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(140), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [867] = 2,
    ACTIONS(46), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(44), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [882] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(148), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(146), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [899] = 2,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(13), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [914] = 2,
    ACTIONS(42), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
    ACTIONS(40), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [929] = 4,
    ACTIONS(36), 1,
      aux_sym_identifier_token2,
    ACTIONS(150), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      sym__semi_colon,
    ACTIONS(34), 7,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [948] = 3,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(32), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [965] = 5,
    ACTIONS(30), 1,
      sym__operator,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym__semi_colon,
    ACTIONS(154), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [986] = 5,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    ACTIONS(158), 1,
      sym__operator,
    STATE(84), 1,
      sym__semi_colon,
    ACTIONS(154), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1007] = 3,
    ACTIONS(148), 1,
      aux_sym_identifier_token2,
    ACTIONS(160), 1,
      sym__operator,
    ACTIONS(146), 7,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1023] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(98), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1049] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(112), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1075] = 4,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym__semi_colon,
    ACTIONS(154), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1093] = 2,
    ACTIONS(42), 1,
      aux_sym_identifier_token2,
    ACTIONS(40), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1107] = 3,
    ACTIONS(158), 1,
      sym__operator,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(148), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1123] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(70), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1149] = 3,
    ACTIONS(158), 1,
      sym__operator,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(142), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1165] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(132), 1,
      sym_function_name,
    STATE(135), 1,
      sym_factor,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1191] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(111), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1217] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(91), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1243] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(115), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1269] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(36), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1295] = 2,
    ACTIONS(46), 1,
      aux_sym_identifier_token2,
    ACTIONS(44), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1309] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(34), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1335] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(132), 1,
      sym_function_name,
    STATE(139), 1,
      sym_factor,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1361] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(109), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1387] = 2,
    ACTIONS(50), 1,
      aux_sym_identifier_token2,
    ACTIONS(48), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1401] = 2,
    ACTIONS(30), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(32), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1415] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(97), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1441] = 8,
    ACTIONS(114), 1,
      aux_sym_identifier_token1,
    ACTIONS(116), 1,
      aux_sym_identifier_token2,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    STATE(40), 1,
      sym_identifier,
    STATE(50), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(61), 2,
      sym_operation,
      sym_function_call,
  [1467] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(132), 1,
      sym_function_name,
    STATE(133), 1,
      sym_factor,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1493] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(101), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1519] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(110), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1545] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(72), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(43), 1,
      sym_factor,
    STATE(126), 1,
      sym_function_name,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1571] = 8,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(62), 1,
      sym__number,
    ACTIONS(162), 1,
      sym__not,
    STATE(5), 1,
      sym_identifier,
    STATE(132), 1,
      sym_function_name,
    STATE(138), 1,
      sym_factor,
    STATE(7), 2,
      sym_operation,
      sym_function_call,
  [1597] = 8,
    ACTIONS(114), 1,
      aux_sym_identifier_token1,
    ACTIONS(116), 1,
      aux_sym_identifier_token2,
    ACTIONS(118), 1,
      sym__number,
    ACTIONS(122), 1,
      sym__not,
    STATE(40), 1,
      sym_identifier,
    STATE(48), 1,
      sym_factor,
    STATE(132), 1,
      sym_function_name,
    STATE(61), 2,
      sym_operation,
      sym_function_call,
  [1623] = 3,
    ACTIONS(142), 1,
      aux_sym_identifier_token2,
    ACTIONS(160), 1,
      sym__operator,
    ACTIONS(140), 7,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      aux_sym_identifier_token1,
      anon_sym_SEMI,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1639] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(90), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1665] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(102), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1691] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(96), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1717] = 8,
    ACTIONS(64), 1,
      sym__not,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
    ACTIONS(128), 1,
      aux_sym_identifier_token2,
    ACTIONS(130), 1,
      sym__number,
    STATE(23), 1,
      sym_identifier,
    STATE(92), 1,
      sym_factor,
    STATE(129), 1,
      sym_function_name,
    STATE(32), 2,
      sym_operation,
      sym_function_call,
  [1743] = 2,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(166), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1756] = 2,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 7,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
      sym__function_keyword,
  [1769] = 4,
    ACTIONS(160), 1,
      sym__operator,
    ACTIONS(176), 1,
      aux_sym_identifier_token2,
    ACTIONS(172), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(174), 4,
      aux_sym_identifier_token1,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [1786] = 2,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(180), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1799] = 2,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(184), 7,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
      sym__function_keyword,
  [1812] = 5,
    ACTIONS(56), 1,
      sym__end,
    STATE(86), 1,
      sym_block,
    STATE(136), 1,
      sym_identifier,
    ACTIONS(7), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(89), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [1830] = 2,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(188), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1842] = 3,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym__eq,
    ACTIONS(30), 5,
      sym__operator,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [1856] = 4,
    ACTIONS(160), 1,
      sym__operator,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      aux_sym_identifier_token2,
    ACTIONS(192), 4,
      anon_sym_RPAREN,
      aux_sym_identifier_token1,
      sym__number,
      sym__not,
  [1872] = 2,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    ACTIONS(200), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1884] = 2,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1896] = 2,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
    ACTIONS(208), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1908] = 2,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
    ACTIONS(212), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1920] = 2,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
    ACTIONS(216), 6,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__function_keyword,
  [1932] = 4,
    ACTIONS(218), 1,
      sym__end,
    STATE(136), 1,
      sym_identifier,
    ACTIONS(7), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(93), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [1947] = 4,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(224), 1,
      sym__comparator_equal,
    ACTIONS(222), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [1962] = 4,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    ACTIONS(230), 1,
      sym__comparator_equal,
    ACTIONS(228), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [1977] = 4,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    ACTIONS(236), 1,
      sym__comparator_equal,
    ACTIONS(234), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [1992] = 4,
    ACTIONS(241), 1,
      sym__end,
    STATE(136), 1,
      sym_identifier,
    ACTIONS(238), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(93), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [2007] = 4,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    STATE(119), 1,
      sym__semi_colon,
    ACTIONS(154), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2022] = 4,
    ACTIONS(30), 1,
      sym__operator,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    STATE(119), 1,
      sym__semi_colon,
    ACTIONS(154), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2037] = 4,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(249), 1,
      sym__comparator_equal,
    ACTIONS(247), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2052] = 3,
    ACTIONS(251), 1,
      sym__operator,
    ACTIONS(255), 1,
      sym__comparator_equal,
    ACTIONS(253), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2064] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(222), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2076] = 5,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(104), 1,
      aux_sym_parameter_list_repeat1,
    STATE(117), 1,
      sym_identifier,
  [2092] = 5,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    ACTIONS(261), 1,
      aux_sym_identifier_token1,
    ACTIONS(264), 1,
      aux_sym_identifier_token2,
    STATE(100), 1,
      aux_sym_parameter_list_repeat1,
    STATE(117), 1,
      sym_identifier,
  [2108] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2120] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2132] = 3,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    STATE(119), 1,
      sym__semi_colon,
    ACTIONS(154), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2144] = 5,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(100), 1,
      aux_sym_parameter_list_repeat1,
    STATE(117), 1,
      sym_identifier,
  [2160] = 2,
    ACTIONS(273), 1,
      aux_sym_identifier_token2,
    ACTIONS(105), 4,
      aux_sym_identifier_token1,
      sym__number,
      anon_sym_RBRACK,
      sym__not,
  [2170] = 5,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    STATE(127), 1,
      sym_identifier,
    STATE(130), 1,
      sym_function_name,
    STATE(137), 1,
      sym_return_value,
  [2186] = 2,
    ACTIONS(275), 1,
      aux_sym_identifier_token2,
    ACTIONS(82), 4,
      anon_sym_RPAREN,
      aux_sym_identifier_token1,
      sym__number,
      sym__not,
  [2196] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(279), 1,
      sym__comparator_equal,
    ACTIONS(277), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2208] = 2,
    ACTIONS(251), 1,
      sym__operator,
    ACTIONS(140), 4,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [2218] = 3,
    ACTIONS(144), 1,
      sym__operator,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    ACTIONS(283), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2230] = 2,
    ACTIONS(251), 1,
      sym__operator,
    ACTIONS(146), 4,
      sym__and,
      sym__or,
      sym__diff,
      sym__comparator_equal,
  [2240] = 2,
    ACTIONS(251), 1,
      sym__operator,
    ACTIONS(285), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2249] = 4,
    ACTIONS(7), 1,
      aux_sym_identifier_token2,
    ACTIONS(60), 1,
      aux_sym_identifier_token1,
    STATE(128), 1,
      sym_function_name,
    STATE(134), 1,
      sym_identifier,
  [2262] = 2,
    ACTIONS(164), 1,
      anon_sym_SEMI,
    ACTIONS(166), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2271] = 2,
    ACTIONS(251), 1,
      sym__operator,
    ACTIONS(287), 3,
      sym__and,
      sym__or,
      sym__diff,
  [2280] = 2,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    ACTIONS(180), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2289] = 3,
    ACTIONS(291), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      aux_sym_identifier_token2,
    ACTIONS(289), 2,
      anon_sym_RPAREN,
      aux_sym_identifier_token1,
  [2300] = 1,
    ACTIONS(269), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2306] = 1,
    ACTIONS(200), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2312] = 1,
    ACTIONS(295), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2318] = 1,
    ACTIONS(228), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2324] = 2,
    ACTIONS(297), 1,
      aux_sym_identifier_token2,
    ACTIONS(259), 2,
      anon_sym_RPAREN,
      aux_sym_identifier_token1,
  [2332] = 1,
    ACTIONS(222), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2338] = 1,
    ACTIONS(247), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2344] = 1,
    ACTIONS(283), 3,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
      sym__end,
  [2350] = 2,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      sym_argument_list,
  [2357] = 2,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(301), 1,
      sym__eq,
  [2364] = 2,
    ACTIONS(303), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_parameter_list,
  [2371] = 2,
    ACTIONS(305), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_argument_list,
  [2378] = 2,
    ACTIONS(303), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_parameter_list,
  [2385] = 2,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(307), 1,
      sym__eq,
  [2392] = 2,
    ACTIONS(309), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_argument_list,
  [2399] = 1,
    ACTIONS(311), 1,
      sym__operator,
  [2403] = 1,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
  [2407] = 1,
    ACTIONS(313), 1,
      sym__operator,
  [2411] = 1,
    ACTIONS(315), 1,
      sym__eq,
  [2415] = 1,
    ACTIONS(317), 1,
      sym__eq,
  [2419] = 1,
    ACTIONS(319), 1,
      sym__operator,
  [2423] = 1,
    ACTIONS(321), 1,
      sym__operator,
  [2427] = 1,
    ACTIONS(323), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 105,
  [SMALL_STATE(7)] = 128,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 164,
  [SMALL_STATE(10)] = 182,
  [SMALL_STATE(11)] = 200,
  [SMALL_STATE(12)] = 227,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 287,
  [SMALL_STATE(15)] = 314,
  [SMALL_STATE(16)] = 330,
  [SMALL_STATE(17)] = 362,
  [SMALL_STATE(18)] = 394,
  [SMALL_STATE(19)] = 426,
  [SMALL_STATE(20)] = 458,
  [SMALL_STATE(21)] = 490,
  [SMALL_STATE(22)] = 522,
  [SMALL_STATE(23)] = 554,
  [SMALL_STATE(24)] = 572,
  [SMALL_STATE(25)] = 604,
  [SMALL_STATE(26)] = 636,
  [SMALL_STATE(27)] = 670,
  [SMALL_STATE(28)] = 690,
  [SMALL_STATE(29)] = 724,
  [SMALL_STATE(30)] = 756,
  [SMALL_STATE(31)] = 788,
  [SMALL_STATE(32)] = 820,
  [SMALL_STATE(33)] = 835,
  [SMALL_STATE(34)] = 850,
  [SMALL_STATE(35)] = 867,
  [SMALL_STATE(36)] = 882,
  [SMALL_STATE(37)] = 899,
  [SMALL_STATE(38)] = 914,
  [SMALL_STATE(39)] = 929,
  [SMALL_STATE(40)] = 948,
  [SMALL_STATE(41)] = 965,
  [SMALL_STATE(42)] = 986,
  [SMALL_STATE(43)] = 1007,
  [SMALL_STATE(44)] = 1023,
  [SMALL_STATE(45)] = 1049,
  [SMALL_STATE(46)] = 1075,
  [SMALL_STATE(47)] = 1093,
  [SMALL_STATE(48)] = 1107,
  [SMALL_STATE(49)] = 1123,
  [SMALL_STATE(50)] = 1149,
  [SMALL_STATE(51)] = 1165,
  [SMALL_STATE(52)] = 1191,
  [SMALL_STATE(53)] = 1217,
  [SMALL_STATE(54)] = 1243,
  [SMALL_STATE(55)] = 1269,
  [SMALL_STATE(56)] = 1295,
  [SMALL_STATE(57)] = 1309,
  [SMALL_STATE(58)] = 1335,
  [SMALL_STATE(59)] = 1361,
  [SMALL_STATE(60)] = 1387,
  [SMALL_STATE(61)] = 1401,
  [SMALL_STATE(62)] = 1415,
  [SMALL_STATE(63)] = 1441,
  [SMALL_STATE(64)] = 1467,
  [SMALL_STATE(65)] = 1493,
  [SMALL_STATE(66)] = 1519,
  [SMALL_STATE(67)] = 1545,
  [SMALL_STATE(68)] = 1571,
  [SMALL_STATE(69)] = 1597,
  [SMALL_STATE(70)] = 1623,
  [SMALL_STATE(71)] = 1639,
  [SMALL_STATE(72)] = 1665,
  [SMALL_STATE(73)] = 1691,
  [SMALL_STATE(74)] = 1717,
  [SMALL_STATE(75)] = 1743,
  [SMALL_STATE(76)] = 1756,
  [SMALL_STATE(77)] = 1769,
  [SMALL_STATE(78)] = 1786,
  [SMALL_STATE(79)] = 1799,
  [SMALL_STATE(80)] = 1812,
  [SMALL_STATE(81)] = 1830,
  [SMALL_STATE(82)] = 1842,
  [SMALL_STATE(83)] = 1856,
  [SMALL_STATE(84)] = 1872,
  [SMALL_STATE(85)] = 1884,
  [SMALL_STATE(86)] = 1896,
  [SMALL_STATE(87)] = 1908,
  [SMALL_STATE(88)] = 1920,
  [SMALL_STATE(89)] = 1932,
  [SMALL_STATE(90)] = 1947,
  [SMALL_STATE(91)] = 1962,
  [SMALL_STATE(92)] = 1977,
  [SMALL_STATE(93)] = 1992,
  [SMALL_STATE(94)] = 2007,
  [SMALL_STATE(95)] = 2022,
  [SMALL_STATE(96)] = 2037,
  [SMALL_STATE(97)] = 2052,
  [SMALL_STATE(98)] = 2064,
  [SMALL_STATE(99)] = 2076,
  [SMALL_STATE(100)] = 2092,
  [SMALL_STATE(101)] = 2108,
  [SMALL_STATE(102)] = 2120,
  [SMALL_STATE(103)] = 2132,
  [SMALL_STATE(104)] = 2144,
  [SMALL_STATE(105)] = 2160,
  [SMALL_STATE(106)] = 2170,
  [SMALL_STATE(107)] = 2186,
  [SMALL_STATE(108)] = 2196,
  [SMALL_STATE(109)] = 2208,
  [SMALL_STATE(110)] = 2218,
  [SMALL_STATE(111)] = 2230,
  [SMALL_STATE(112)] = 2240,
  [SMALL_STATE(113)] = 2249,
  [SMALL_STATE(114)] = 2262,
  [SMALL_STATE(115)] = 2271,
  [SMALL_STATE(116)] = 2280,
  [SMALL_STATE(117)] = 2289,
  [SMALL_STATE(118)] = 2300,
  [SMALL_STATE(119)] = 2306,
  [SMALL_STATE(120)] = 2312,
  [SMALL_STATE(121)] = 2318,
  [SMALL_STATE(122)] = 2324,
  [SMALL_STATE(123)] = 2332,
  [SMALL_STATE(124)] = 2338,
  [SMALL_STATE(125)] = 2344,
  [SMALL_STATE(126)] = 2350,
  [SMALL_STATE(127)] = 2357,
  [SMALL_STATE(128)] = 2364,
  [SMALL_STATE(129)] = 2371,
  [SMALL_STATE(130)] = 2378,
  [SMALL_STATE(131)] = 2385,
  [SMALL_STATE(132)] = 2392,
  [SMALL_STATE(133)] = 2399,
  [SMALL_STATE(134)] = 2403,
  [SMALL_STATE(135)] = 2407,
  [SMALL_STATE(136)] = 2411,
  [SMALL_STATE(137)] = 2415,
  [SMALL_STATE(138)] = 2419,
  [SMALL_STATE(139)] = 2423,
  [SMALL_STATE(140)] = 2427,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(106),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(2),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(7),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(51),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(2),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(7),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(51),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 3),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 4),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_definition, 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector_definition, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_vector_definition_repeat1, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_definition, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector_definition, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_structure, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 6),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 4),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(2),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 5),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(2),
  [264] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 8),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_vector_definition_repeat1, 2),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 7),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 9),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_value, 1),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [323] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_matlab(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
