#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LPAREN = 1,
  anon_sym_COMMA = 2,
  anon_sym_RPAREN = 3,
  sym_identifier = 4,
  anon_sym_SEMI = 5,
  sym__eq = 6,
  sym__operator = 7,
  sym__number = 8,
  sym__end = 9,
  sym__function_keyword = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_source_file = 13,
  sym_function_definition = 14,
  sym_operation = 15,
  sym_expression = 16,
  sym_parameter_list = 17,
  sym_argument_list = 18,
  sym_function_name = 19,
  sym_return_value = 20,
  sym_block = 21,
  sym_factor = 22,
  sym_function_call = 23,
  sym__semi_colon = 24,
  sym_vector_definition = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_parameter_list_repeat1 = 27,
  aux_sym_argument_list_repeat1 = 28,
  aux_sym_block_repeat1 = 29,
  aux_sym_vector_definition_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [sym__eq] = "_eq",
  [sym__operator] = "_operator",
  [sym__number] = "_number",
  [sym__end] = "_end",
  [sym__function_keyword] = "_function_keyword",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_function_definition] = "function_definition",
  [sym_operation] = "operation",
  [sym_expression] = "expression",
  [sym_parameter_list] = "parameter_list",
  [sym_argument_list] = "argument_list",
  [sym_function_name] = "function_name",
  [sym_return_value] = "return_value",
  [sym_block] = "block",
  [sym_factor] = "factor",
  [sym_function_call] = "function_call",
  [sym__semi_colon] = "_semi_colon",
  [sym_vector_definition] = "vector_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_vector_definition_repeat1] = "vector_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__eq] = sym__eq,
  [sym__operator] = sym__operator,
  [sym__number] = sym__number,
  [sym__end] = sym__end,
  [sym__function_keyword] = sym__function_keyword,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_function_definition] = sym_function_definition,
  [sym_operation] = sym_operation,
  [sym_expression] = sym_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_argument_list] = sym_argument_list,
  [sym_function_name] = sym_function_name,
  [sym_return_value] = sym_return_value,
  [sym_block] = sym_block,
  [sym_factor] = sym_factor,
  [sym_function_call] = sym_function_call,
  [sym__semi_colon] = sym__semi_colon,
  [sym_vector_definition] = sym_vector_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_vector_definition_repeat1] = aux_sym_vector_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__eq] = {
    .visible = false,
    .named = true,
  },
  [sym__operator] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym__end] = {
    .visible = false,
    .named = true,
  },
  [sym__function_keyword] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym_return_value] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__semi_colon] = {
    .visible = false,
    .named = true,
  },
  [sym_vector_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(7);
      if (lookahead == ',') ADVANCE(6);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          lookahead == ':' ||
          lookahead == '^') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(7);
      if (lookahead == ',') ADVANCE(6);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          lookahead == ':' ||
          lookahead == '^') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          lookahead == ':' ||
          lookahead == '^') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          lookahead == ':' ||
          lookahead == '^') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__eq);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__operator);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__end);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__function_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym__eq] = ACTIONS(1),
    [sym__operator] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym__end] = ACTIONS(1),
    [sym__function_keyword] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym_function_definition] = STATE(14),
    [sym_expression] = STATE(14),
    [sym_function_name] = STATE(79),
    [sym_function_call] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym__function_keyword] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      sym__semi_colon,
    ACTIONS(9), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
  [15] = 7,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [38] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      aux_sym_vector_definition_repeat1,
    STATE(28), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [61] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(21), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [84] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [107] = 8,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym__number,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    STATE(32), 1,
      sym_operation,
    STATE(33), 1,
      sym_factor,
    STATE(35), 1,
      sym_vector_definition,
    STATE(36), 1,
      sym_function_call,
    STATE(79), 1,
      sym_function_name,
  [132] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(4), 1,
      aux_sym_vector_definition_repeat1,
    STATE(28), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [155] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [178] = 8,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym__number,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      sym_factor,
    STATE(38), 1,
      sym_operation,
    STATE(53), 1,
      sym_function_call,
    STATE(55), 1,
      sym_vector_definition,
    STATE(80), 1,
      sym_function_name,
  [203] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym_vector_definition_repeat1,
    STATE(28), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [226] = 7,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym__number,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [249] = 5,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(56), 1,
      sym__function_keyword,
    STATE(79), 1,
      sym_function_name,
    STATE(13), 4,
      sym_function_definition,
      sym_expression,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [268] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym__function_keyword,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(79), 1,
      sym_function_name,
    STATE(13), 4,
      sym_function_definition,
      sym_expression,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [287] = 7,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(64), 1,
      sym__number,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      aux_sym_vector_definition_repeat1,
    STATE(28), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [310] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [333] = 2,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
  [346] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      aux_sym_vector_definition_repeat1,
    STATE(28), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [369] = 7,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      aux_sym_argument_list_repeat1,
    STATE(43), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [392] = 6,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      sym__end,
    ACTIONS(85), 1,
      sym__function_keyword,
    STATE(71), 1,
      sym_block,
    STATE(52), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [412] = 6,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      sym__end,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      sym__function_keyword,
    STATE(59), 1,
      sym_block,
    STATE(52), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [432] = 1,
    ACTIONS(73), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
  [442] = 1,
    ACTIONS(91), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
  [452] = 1,
    ACTIONS(93), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
  [462] = 1,
    ACTIONS(95), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_SEMI,
      sym__operator,
      sym__number,
      anon_sym_RBRACK,
  [472] = 2,
    ACTIONS(99), 1,
      sym__operator,
    ACTIONS(97), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_SEMI,
      sym__number,
      anon_sym_RBRACK,
  [484] = 3,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 2,
      sym_identifier,
      sym__function_keyword,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
  [497] = 3,
    ACTIONS(99), 1,
      sym__operator,
    ACTIONS(103), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
    ACTIONS(105), 3,
      sym_identifier,
      sym__number,
      anon_sym_RBRACK,
  [510] = 5,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym__number,
    STATE(26), 1,
      sym_factor,
    STATE(75), 1,
      sym_function_name,
    STATE(22), 2,
      sym_operation,
      sym_function_call,
  [527] = 5,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym__number,
    STATE(45), 1,
      sym_factor,
    STATE(79), 1,
      sym_function_name,
    STATE(36), 2,
      sym_operation,
      sym_function_call,
  [544] = 5,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym__number,
    STATE(49), 1,
      sym_factor,
    STATE(80), 1,
      sym_function_name,
    STATE(53), 2,
      sym_operation,
      sym_function_call,
  [561] = 5,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      sym__semi_colon,
    ACTIONS(109), 2,
      sym_identifier,
      sym__function_keyword,
  [578] = 5,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    ACTIONS(113), 1,
      sym__operator,
    STATE(64), 1,
      sym__semi_colon,
    ACTIONS(109), 2,
      sym_identifier,
      sym__function_keyword,
  [595] = 4,
    ACTIONS(117), 1,
      anon_sym_SEMI,
    STATE(41), 1,
      sym__semi_colon,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      sym__operator,
    ACTIONS(115), 2,
      sym_identifier,
      sym__function_keyword,
  [610] = 4,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      sym__semi_colon,
    ACTIONS(109), 2,
      sym_identifier,
      sym__function_keyword,
  [624] = 2,
    ACTIONS(101), 2,
      sym_identifier,
      sym__function_keyword,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
  [634] = 4,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    ACTIONS(121), 1,
      sym__operator,
    STATE(74), 1,
      sym__semi_colon,
    ACTIONS(109), 2,
      sym_identifier,
      sym__end,
  [648] = 4,
    ACTIONS(73), 1,
      sym__operator,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    STATE(74), 1,
      sym__semi_colon,
    ACTIONS(109), 2,
      sym_identifier,
      sym__end,
  [662] = 3,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 2,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(101), 2,
      sym_identifier,
      sym__end,
  [674] = 4,
    ACTIONS(9), 1,
      sym__operator,
    ACTIONS(123), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      sym__semi_colon,
    ACTIONS(115), 2,
      sym_identifier,
      sym__end,
  [688] = 2,
    ACTIONS(125), 2,
      sym_identifier,
      sym__function_keyword,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
  [698] = 2,
    ACTIONS(127), 2,
      sym_identifier,
      sym__function_keyword,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
  [708] = 3,
    ACTIONS(99), 1,
      sym__operator,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(131), 3,
      anon_sym_RPAREN,
      sym_identifier,
      sym__number,
  [720] = 2,
    ACTIONS(133), 2,
      sym_identifier,
      sym__function_keyword,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym__operator,
  [730] = 3,
    ACTIONS(113), 1,
      sym__operator,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(135), 2,
      sym_identifier,
      sym__function_keyword,
  [742] = 2,
    ACTIONS(95), 2,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(133), 2,
      sym_identifier,
      sym__end,
  [751] = 2,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 3,
      sym_identifier,
      sym__end,
      sym__function_keyword,
  [760] = 3,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(144), 1,
      sym__end,
    STATE(48), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [771] = 3,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(121), 1,
      sym__operator,
    ACTIONS(135), 2,
      sym_identifier,
      sym__end,
  [782] = 2,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(148), 2,
      sym_identifier,
      sym__function_keyword,
  [791] = 2,
    ACTIONS(93), 2,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(127), 2,
      sym_identifier,
      sym__end,
  [800] = 3,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym__end,
    STATE(48), 2,
      sym_expression,
      aux_sym_block_repeat1,
  [811] = 2,
    ACTIONS(73), 2,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(101), 2,
      sym_identifier,
      sym__end,
  [820] = 2,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(154), 2,
      sym_identifier,
      sym__function_keyword,
  [829] = 3,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    STATE(74), 1,
      sym__semi_colon,
    ACTIONS(109), 2,
      sym_identifier,
      sym__end,
  [840] = 2,
    ACTIONS(91), 2,
      anon_sym_SEMI,
      sym__operator,
    ACTIONS(125), 2,
      sym_identifier,
      sym__end,
  [849] = 2,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 3,
      sym_identifier,
      sym__end,
      sym__function_keyword,
  [858] = 3,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(69), 1,
      aux_sym_parameter_list_repeat1,
  [868] = 2,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 2,
      sym_identifier,
      sym__function_keyword,
  [876] = 3,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 1,
      sym_identifier,
    STATE(60), 1,
      aux_sym_parameter_list_repeat1,
  [886] = 2,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 2,
      sym_identifier,
      sym__function_keyword,
  [894] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(77), 1,
      sym_function_name,
    STATE(84), 1,
      sym_return_value,
  [904] = 2,
    ACTIONS(152), 1,
      anon_sym_SEMI,
    ACTIONS(154), 2,
      sym_identifier,
      sym__end,
  [912] = 2,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    ACTIONS(181), 2,
      sym_identifier,
      sym__function_keyword,
  [920] = 1,
    ACTIONS(67), 3,
      sym_identifier,
      sym__number,
      anon_sym_RBRACK,
  [926] = 2,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [934] = 2,
    ACTIONS(146), 1,
      anon_sym_SEMI,
    ACTIONS(148), 2,
      sym_identifier,
      sym__end,
  [942] = 1,
    ACTIONS(43), 3,
      anon_sym_RPAREN,
      sym_identifier,
      sym__number,
  [948] = 3,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_parameter_list_repeat1,
  [958] = 2,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 2,
      sym_identifier,
      sym__function_keyword,
  [966] = 2,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 2,
      sym_identifier,
      sym__function_keyword,
  [974] = 2,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_parameter_list,
  [981] = 2,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(199), 1,
      sym__eq,
  [988] = 1,
    ACTIONS(181), 2,
      sym_identifier,
      sym__end,
  [993] = 2,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
    STATE(2), 1,
      sym_argument_list,
  [1000] = 2,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(72), 1,
      sym_function_name,
  [1007] = 2,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_parameter_list,
  [1014] = 2,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(205), 1,
      sym__eq,
  [1021] = 2,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_argument_list,
  [1028] = 2,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    STATE(40), 1,
      sym_argument_list,
  [1035] = 1,
    ACTIONS(168), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1040] = 1,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
  [1044] = 1,
    ACTIONS(211), 1,
      sym__eq,
  [1048] = 1,
    ACTIONS(213), 1,
      sym__eq,
  [1052] = 1,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 61,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 132,
  [SMALL_STATE(9)] = 155,
  [SMALL_STATE(10)] = 178,
  [SMALL_STATE(11)] = 203,
  [SMALL_STATE(12)] = 226,
  [SMALL_STATE(13)] = 249,
  [SMALL_STATE(14)] = 268,
  [SMALL_STATE(15)] = 287,
  [SMALL_STATE(16)] = 310,
  [SMALL_STATE(17)] = 333,
  [SMALL_STATE(18)] = 346,
  [SMALL_STATE(19)] = 369,
  [SMALL_STATE(20)] = 392,
  [SMALL_STATE(21)] = 412,
  [SMALL_STATE(22)] = 432,
  [SMALL_STATE(23)] = 442,
  [SMALL_STATE(24)] = 452,
  [SMALL_STATE(25)] = 462,
  [SMALL_STATE(26)] = 472,
  [SMALL_STATE(27)] = 484,
  [SMALL_STATE(28)] = 497,
  [SMALL_STATE(29)] = 510,
  [SMALL_STATE(30)] = 527,
  [SMALL_STATE(31)] = 544,
  [SMALL_STATE(32)] = 561,
  [SMALL_STATE(33)] = 578,
  [SMALL_STATE(34)] = 595,
  [SMALL_STATE(35)] = 610,
  [SMALL_STATE(36)] = 624,
  [SMALL_STATE(37)] = 634,
  [SMALL_STATE(38)] = 648,
  [SMALL_STATE(39)] = 662,
  [SMALL_STATE(40)] = 674,
  [SMALL_STATE(41)] = 688,
  [SMALL_STATE(42)] = 698,
  [SMALL_STATE(43)] = 708,
  [SMALL_STATE(44)] = 720,
  [SMALL_STATE(45)] = 730,
  [SMALL_STATE(46)] = 742,
  [SMALL_STATE(47)] = 751,
  [SMALL_STATE(48)] = 760,
  [SMALL_STATE(49)] = 771,
  [SMALL_STATE(50)] = 782,
  [SMALL_STATE(51)] = 791,
  [SMALL_STATE(52)] = 800,
  [SMALL_STATE(53)] = 811,
  [SMALL_STATE(54)] = 820,
  [SMALL_STATE(55)] = 829,
  [SMALL_STATE(56)] = 840,
  [SMALL_STATE(57)] = 849,
  [SMALL_STATE(58)] = 858,
  [SMALL_STATE(59)] = 868,
  [SMALL_STATE(60)] = 876,
  [SMALL_STATE(61)] = 886,
  [SMALL_STATE(62)] = 894,
  [SMALL_STATE(63)] = 904,
  [SMALL_STATE(64)] = 912,
  [SMALL_STATE(65)] = 920,
  [SMALL_STATE(66)] = 926,
  [SMALL_STATE(67)] = 934,
  [SMALL_STATE(68)] = 942,
  [SMALL_STATE(69)] = 948,
  [SMALL_STATE(70)] = 958,
  [SMALL_STATE(71)] = 966,
  [SMALL_STATE(72)] = 974,
  [SMALL_STATE(73)] = 981,
  [SMALL_STATE(74)] = 988,
  [SMALL_STATE(75)] = 993,
  [SMALL_STATE(76)] = 1000,
  [SMALL_STATE(77)] = 1007,
  [SMALL_STATE(78)] = 1014,
  [SMALL_STATE(79)] = 1021,
  [SMALL_STATE(80)] = 1028,
  [SMALL_STATE(81)] = 1035,
  [SMALL_STATE(82)] = 1040,
  [SMALL_STATE(83)] = 1044,
  [SMALL_STATE(84)] = 1048,
  [SMALL_STATE(85)] = 1052,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(17),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(22),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(17),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2), SHIFT_REPEAT(22),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_definition_repeat1, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(83),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_definition, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector_definition, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_definition, 2),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector_definition, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(66),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_value, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [215] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_matlab(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
